config/routes.rb
Pdfgenerator::Application.routes.draw do
  
  root :to => "pages#home"
  
  get "wicked_pdf/example", :to => "wicked_pdf#index", :as => "wicked_pdf"
  get "prawn/example", :to => "prawn#index", :as => "prawn"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/prawn_controller.rb
class PrawnController < ApplicationController
  
  def index
    # lets add some test data to show how data flows into our TestPdf class
    page_data = {
      'title' => 'This is the page title',
      'sub_title' => 'Test User | Email: test2@test.com',
      'logo_img' => 'Sonata.jpg'
    }
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TestPdf.new(page_data)
        #Testpdf.page(:size => 'A3', :layout => :portrait)
        # pdf.text "Hello World"
        #Testpdf.page_size "A3"
        #start_new_page(:size => 'A3', :layout => :portrait)
        send_data pdf.render,page_size: 'A3', filename: "example.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
end

app/controllers/wicked_pdf_controller.rb
class WickedPdfController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "wicked_pdf",
          :layout => 'pdf.html'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wicked_pdf_helper.rb
module WickedPdfHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>FINE PDF Generator</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  
  <%= stylesheet_link_tag "main", :media => "all" %>
  <%= stylesheet_link_tag "print", :media => "print" %>
  
  <!--[if lt IE 9]>
    <%= javascript_include_tag "html5shiv", "html5shiv-printshiv" %>
  <![endif]-->
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <section id="container">
    <header>
      <h1>Generate PDF</h1>
    </header>

    <section id="content">
      <%= yield %>
    </section><!-- / content -->
  
  </section><!-- / container -->

</body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>FINE PDF Generator</title>
  
  <%= wicked_pdf_stylesheet_link_tag "main" %>
  <%= wicked_pdf_stylesheet_link_tag "print" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <section id="container">
    <header>
      <h1>FINE PDF Generator Prototype</h1>
      <nav id="main-nav">
        <ul>
          <li><%= link_to " head home", root_path %></li>
        </ul>
      </nav>
    </header>

    <section id="content">
      <%= yield %>
    </section><!-- / content -->
  
  </section><!-- / container -->

</body>
</html>

app/views/pages/home.html.erb
<p>
  
  <%= link_to "Create PDF", prawn_path(:format => 'pdf'), :class => 'pdf_link' %>
</p>

app/views/wicked_pdf/index.pdf.erb
<section class="page" id="page4">
  
	<div class="cover-page">
	  
	  <div class="header cover-header">
  		<%= wicked_pdf_image_tag "fpo-logo.jpg" %>
  		<div class="con">
  		  <span class="client"></span>
  			<h2 class="sell-sheet-title">The Title</h2>
  		</div>
  	</div>
  	<div class="contact">
  		<div class="info">
          <strong>Contact:</strong>
    			<span>Test User</span>
    			
    			<p>Email: <a href="#">test2@test.com</a></p>
    			<a href="#">www.google.com</a>
    			<span class="user-info" data-name="Test User" data-phone="" data-email="test2@test.com"></span>
  		</div>
  		<div class="text">
  		  <div>
        <h3>Nullam In Dui Mauris. Vivamus Hendrerit Arcu Sed Erat</h3>
        <p>Porttitor posuere. Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu. Class aptent taciti.</p>
        </div>
      </div>
  	</div>
  	
	</div><!-- / cover-page -->
	
<div class="printed-products">
	  
	<div class="header">
    <%= wicked_pdf_image_tag "fpo-logo.jpg" %>
    <div class="con">
      <h2>The Title</h2>
      Test User | <span>Email:</span> test2@test.com
    </div>
  </div>

    <div class="wine-big">
  		<div class="left">
  		  <%= wicked_pdf_image_tag "fpo-bottle.png", :class => 'detail' %>
  			
  		</div>
  		<div class="right">
  			<h4>Brand Name</h4>
  			<h3>Example Wine Name 2009</h3>
  			<div class="desc">
  				<strong>REGION:</strong> Italy / Sardinia <br>
  				<br>
  				
  				<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vel ante a orci tempus eleifend ut et magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus.</p><br>
  				
  				
  				
  				  <strong>tasting note</strong><br>
  				  Deep ruby in color, the wine offers intense aromas and flavors of black fruit. It is full-bodied with a velvety texture and balanced tannins.<br><br>
  				
    				<strong>food pairing</strong><br>
    				Pair with lamb or rich pork dishes.<br><br>
  				
  				
  			</div>
  			
				  <div class="points-big">
				    <strong>points of Distinction</strong>
  					<ul>
  						  <li>A modern blend made primarily from the Carignano grape</li>
  						  <li>Matured 15 months in French oak barrels (10% new)</li>
  					</ul>
					</div>
				
				
    			<blockquote>"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vel ante a orci tempus eleifend ut et magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus." </blockquote>
    			<span class="author">– Author</span>
  		</div>
  	</div>
	



  <div class="header">
    <%= wicked_pdf_image_tag "fpo-logo.jpg" %>
    <div class="con">
      <h2>The Title</h2>
      Test User | <span>Email:</span> test2@test.com
    </div>
  </div>

    <div class="wine-big">
  		<div class="left">
  		  <%= wicked_pdf_image_tag "fpo-bottle.png", :class => 'detail' %>
  			
  		</div>
  		<div class="right">
  			<h4>Another Brand</h4>
  			<h3>Pinot Gris 2007</h3>
  			<div class="desc">
  				<strong>REGION:</strong> Argentina / Mendoza <br>
  				<br>
  				
  				<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vel ante a orci tempus eleifend ut et magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus.</p><br>
  				
  				
  				
  				  <strong>tasting note</strong><br>
  				  Shows complex black fruit aromas, with spice and chocolate notes. The flavors are concentrated, yet elegant and expressive, with silky tannins and a long, intense finish.<br><br>
  				
  				
  			</div>
  			
				  <div class="points-big">
				    <strong>points of Distinction</strong>
  					<ul>
  						  <li>Produced from highest quality grapes and only in the best years.</li>
  						  <li>Extremely small yields of only 0.5 bottles per vine.</li>
  						  <li>Limited production.</li>
  					</ul>
					</div>
    			
  		</div>
  	</div>
	



  <div class="header">
    <%= wicked_pdf_image_tag "fpo-logo.jpg" %>
    <div class="con">
      <h2>The Title</h2>
      Test User | <span>Email:</span> test2@test.com
    </div>
  </div>

</div>
	

</section>